{
 "title": "JVM-Spring-micrometer-actuator(good)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)\r\n\r\nFilter by datasource/namespace/node.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(system_load_average_1m{namespace=~\"$namespace\"},app)"
   },
   {
    "name": "podname",
    "label": "Podname",
    "query": "label_values(system_load_average_1m{namespace=~\"$namespace\",app=~\"$application\"},pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"heap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "System Load  1m %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Rate by URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[5m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Errors by URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", status!=\"2..\"}[5m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Client Errors by URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_max{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", status!=\"2..\"}[5m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Client Success Calls by URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", status=~\"2..\"}[5m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"heap\"})",
     "legendFormat": "{{app}} :used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"heap\"})",
     "legendFormat": "{{app}}:committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"heap\"})",
     "legendFormat": "{{app}}:max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"nonheap\"})",
     "legendFormat": "{{app}}:used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"nonheap\"})",
     "legendFormat": "{{app}}:committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", area=\"nonheap\"})",
     "legendFormat": "{{app}}:max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"})",
     "legendFormat": "{{app}}:used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"})",
     "legendFormat": "{{app}}:committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"})",
     "legendFormat": "{{app}}:max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_rss_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-rss"
    },
    {
     "expr": "process_memory_swap_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-swap"
    },
    {
     "expr": "process_memory_rss_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"} + process_memory_swap_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-total"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-Sys"
    },
    {
     "expr": "process_cpu_usage{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-Proc"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[1h])",
     "legendFormat": "{{app}}-Proc1H"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:system-1m"
    },
    {
     "expr": "system_cpu_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:peak"
    },
    {
     "expr": "process_threads{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{app}}:{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:open"
    },
    {
     "expr": "process_files_max_files{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }, "repeat": "persistence_counts" },
  {
   "title": "JVM Pool Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-U"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-C"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-M"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true
  },
  {
   "title": "JVM Pool Non Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-U"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-C"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}-M"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{app}}:{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[1m])/rate(jvm_gc_pause_seconds_count{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[1m])",
     "legendFormat": "{{app}}:avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}:max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[1m])",
     "legendFormat": "{{app}}-All"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[1m])",
     "legendFormat": "{{app}}-prom"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", id=\"direct\"}",
     "legendFormat": "{{app}}-U"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", id=\"direct\"}",
     "legendFormat": "{{app}}-C"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", id=\"direct\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", id=\"mapped\"}",
     "legendFormat": "{{app}}-U"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", id=\"mapped\"}",
     "legendFormat": "{{app}}-C"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=~\"$namespace\",app=~\"$application\", pod_name=~\"$podname\", id=\"mapped\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}